name: PHPCS Auto-fix and Commit

on:
  push:
    branches:
      - feature/phpcs

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - name: PHPCS lint and auto-fix
        run: |
          vendor/bin/phpcs --standard=PSR2 -n -p .
          vendor/bin/phpcbf --standard=PSR2 -n -p .

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-fix PHPCS issues" || true

      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          branch: ${{ github.ref }}
